=== Islem-123/IslemMessaoud_LSI3_TP2_SOA/src/xsd/ServiceBanque.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/BanqueService" xmlns:tns="http://www.example.org/BanqueService" elementFormDefault="qualified" >
<element name="BanqueService">
	<complexType>
		<sequence>
				<element name="conversion" type="tns:conversiontype"></element>
				<element name="getCompte" type="tns:Comptetype"></element>
				<element name="getComptes" type="tns:Comptetype" minOccurs="1" maxOccurs="unbounded"></element>
				<!-- minoccurs hiya akal haja maxoccurs hiya infini = unbounded  -->
		</sequence>
</complexType>
</element>

<complexType name="conversiontype">
	<sequence>
		<element name="montant" type="double"></element>
	</sequence>
</complexType>

        <complexType name="Comptetype">
            <sequence>
                <element name="code" type="int"/>
                <element name="solde" type="double"/>
                <element name="dateCreat" type="date"/>
            </sequence>
        </complexType>
  </schema>

=== Islem-123/IslemMessaoud_LSI3_TP2_SOA/src/xsd/BanqueService.xml
<?xml version="1.0" encoding="UTF-8"?>
<BanqueService xmlns:tns="http://www.example.org/BanqueService" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/BanqueService ServiceBanque.xsd ">
  <conversion>
    <montant>25.000</montant>
  </conversion>
  <getCompte>
    <code>5</code>
    <solde>25.00</solde>
    <dateCreat>2001-01-01</dateCreat>
  </getCompte>
  <getComptes>
    <code>12</code>
    <solde>503.00</solde>
    <dateCreat>1987-01-01</dateCreat>
  </getComptes>
  <getComptes>
    <code>2</code>
    <solde>253.66</solde>
    <dateCreat>1896-01-01</dateCreat>
  </getComptes>
</BanqueService>
